language: node_js

sudo: required

node_js:
  - '10'

os: linux

install:
  - yarn

script:
  - npm run lint

before_deploy:
  - cd ./examples && yarn && npm run build

deploy:
  provider: pages
  local_dir: ./examples/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master

branches:
  only:
    - master

cache:
  yarn: true
